### ISSUE TITLE
unable to add menu item & custom menu items columns not working

### ISSUE THREAD

**Issue by AlizHarb** [datlechin/filament-menu-builder#28]
### What happened?

Hello
I have installed the plugin today and was trying to figure out how it works.
first of all i have added 3 new columns to the `menu_items` table (icon, timer, extra)
```php
\Datlechin\FilamentMenuBuilder\FilamentMenuBuilderPlugin::make()
    ->addMenuItemFields([
        Components\TextInput::make('icon'),
        Components\TextInput::make('time'),
        Components\TextInput::make('extra'),
    ])
```
this is not showing the new columns in `menu items` form
![image](https://github.com/user-attachments/assets/549b1d9c-adf6-40cc-a3cf-8620b5c60283)

second issue, when i try to add a menu items it shows me this error
```
SQLSTATE[HY000]: General error: 1 no such table: main.parents (Connection: sqlite, SQL: insert into "menu_items" ("title", "url", "order", "menu_id", "updated_at", "created_at") values (Dashboard, http://127.0.0.1:8000, 1, 1, 2024-09-08 16:54:09, 2024-09-08 16:54:09))
```

thank you

### How to reproduce the bug

when trying to add a new menu items or trying to add new menu items columns

### Package Version

latest

### PHP Version

8.3.6

### Laravel Version

latest

### Which operating systems does with happen with?

Windows

**Comment by datlechin** [comment]
Is your issue resolved?

**Comment by bdsumon4u** [comment]
No, I'm facing the same problem.
![image](https://github.com/user-attachments/assets/7f8c73a9-6a3f-4b1b-9fc9-00474073d79a)

**Comment by AlizHarb** [comment]
> No, I'm facing the same problem. ![image](https://private-user-images.githubusercontent.com/75123992/367599949-7f8c73a9-6a3f-4b1b-9fc9-00474073d79a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjE2NjAsIm5iZiI6MTcyNjQyMTM2MCwicGF0aCI6Ii83NTEyMzk5Mi8zNjc1OTk5NDktN2Y4YzczYTktNmEzZi00YjFiLTlmYzktMDA0NzQwNzNkNzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE3MjkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YmNjYWJkMmI1N2U0Njk2MmI1NGMyNjgwMTFmZmNmYTAzYjg2MWViN2E4NTY5MDIyYjQ1MDIzYjAwMTUwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zzEka0JQEp6FPAFjuQ0OzQr_rNpjvcox6DNd8Mf-VRY)

Hey
You just have to change the `menu_items` relation in the migration file
