### ISSUE TITLE
[Bug]: Missing collapse label

### ISSUE THREAD

**Issue by Senexis** [datlechin/filament-menu-builder#45]
Very simple issue so I'll keep it short. Currently there is a translatable label available for expanding a menu's items with children. However, the inverse is not available. It would be great to have both a `filament-menu-builder::menu-builder.items.expand` label as well as a `filament-menu-builder::menu-builder.items.collapse` label when the group is closed (`!open`).

**Comment by datlechin** [comment]
We can use the native `title` HTML attribute for the collapse/expand button to achieve this.
